server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 500

spring:
  profiles:
    active: local

jwt:
  secret: secretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkey
  expiration-period: 10000
